# StyLua configuration for snacks-bibtex.nvim
# See https://github.com/JohnnyMorganz/StyLua for more information

column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"

[sort_requires]
enabled = false
